# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.twig.calendar_extension:
        class: AppBundle\Twig\CalendarExtension
        tags:
            - { name: twig.extension }

    app.todo_util:
        class: AppBundle\Util\TodoUtil

    app.form_extension.referer:
        class: AppBundle\Form\Extension\RefererUriExtension
        arguments: ["@request_stack"]
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
