<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppointmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointmentRepository extends EntityRepository
{
    public function findAllAndOrderByDate()
    {
        return $this->createQueryBuilder('a')
            ->orderBy('a.epoch')
            ->getQuery()
            ->getResult();
    }
}
